# Generated by Django 5.1 on 2025-01-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='Hotel User',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel Vendor',
        ),
    ]
